version: '3.8'

services:
  # MySQL Server service
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=qpassessment
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=AppUser123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Your application server
  app-server:
    build:
      context: ../  # Points to the project root directory
      dockerfile: deployment/Dockerfile  # Path relative to context
    container_name: app-server
    ports:
      - "2563:2563"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=AppUser123
      - DB_NAME=qpassessment
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge